/**
 * @fileoverview Barrel file for all tool definitions.
 * This file re-exports all tool definitions for easy import and registration.
 * It also exports an array of all definitions for automated registration.
 * @module src/mcp-server/tools/definitions
 */

import {
  batchClickTool,
  camofoxHoverTool,
  camofoxBackTool,
  camofoxClickTool,
  camofoxCloseSessionTool,
  camofoxNavigateAndSnapshotTool,
  camofoxCloseTabGroupTool,
  camofoxCloseTabTool,
  camofoxCreateTabTool,
  camofoxForwardTool,
  camofoxGetLinksTool,
  camofoxGetSnapshotTool,
  camofoxGetStatsTool,
  camofoxHealthTool,
  camofoxImportCookiesTool,
  camofoxListTabsTool,
  camofoxNavigateTabTool,
  camofoxPressTool,
  camofoxRefreshTool,
  camofoxScreenshotTool,
  camofoxScrollAndSnapshotTool,
  camofoxScrollElementTool,
  camofoxScrollTool,
  camofoxStartBrowserTool,
  camofoxStopBrowserTool,
  camofoxTypeTool,
  camofoxWaitForTextTool,
  camofoxWaitTool,
  camofoxYoutubeTranscriptTool,
  closeTabTool,
  createTabTool,
  fillFormTool,
  goBackTool,
  goForwardTool,
  listTabsTool,
  navigateTool,
  refreshTool,
  serverStatusTool,
  snapshotTool,
  typeAndSubmitTool,
  typeTextTool,
  webSearchTool,
} from './camofox-browser.tool.js';

/**
 * An array containing all tool definitions for easy iteration.
 * Includes both regular tools and task-based tools (experimental).
 */
export const allToolDefinitions = [
  camofoxHealthTool,
  serverStatusTool,
  camofoxStartBrowserTool,
  camofoxListTabsTool,
  listTabsTool,
  camofoxCreateTabTool,
  createTabTool,
  camofoxNavigateTabTool,
  navigateTool,
  camofoxNavigateAndSnapshotTool,
  camofoxGetSnapshotTool,
  snapshotTool,
  camofoxWaitTool,
  camofoxWaitForTextTool,
  camofoxClickTool,
  batchClickTool,
  camofoxTypeTool,
  typeTextTool,
  typeAndSubmitTool,
  fillFormTool,
  camofoxHoverTool,
  camofoxPressTool,
  camofoxScrollTool,
  camofoxScrollElementTool,
  camofoxScrollAndSnapshotTool,
  camofoxBackTool,
  goBackTool,
  camofoxForwardTool,
  goForwardTool,
  camofoxRefreshTool,
  refreshTool,
  webSearchTool,
  camofoxGetLinksTool,
  camofoxScreenshotTool,
  camofoxGetStatsTool,
  camofoxCloseTabTool,
  closeTabTool,
  camofoxCloseTabGroupTool,
  camofoxCloseSessionTool,
  camofoxStopBrowserTool,
  camofoxYoutubeTranscriptTool,
  camofoxImportCookiesTool,
];
